log_level = "info"
log_line  = 100

[parallel]
track_mapping = "auto"

[geometry]
path        = "cases/beavrs/single-assembly/geometry.xml"
primitives  = ""
lattice_refines = ""
cell_sectors    = ""

[materials]
path      = "cases/beavrs/beavrs-mgxs.h5"
xs_layout = "named"

[output]
reaction_rates = "F, T, PHI"
cross_sections = "none"
tracks         = "none"
mesh.type      = "rectangle"
mesh.offset    = "0, 0, 0"
mesh.shape     = """\
                 [1.25984]*17,\
                 [1.25984]*17,\
                 [8.0]*5\
                 """

[quadrature]
type         = "Equal Weight"
azims        = 32
azim_spacing = 0.05
polars       = 2
z_spacing    = 0.75

[ray_tracing]
segmentation = "OTF Stacks"
z_mesh       = "Local"
zones        = "-20, 20"
modules      = "1, 1, 1"

[solver]
type           = "CPU Solver"
max_iterations = 1500
tolerance      = 1E-5
stabilization  = "none"
keff_neutron_balance = false
