log_level = "info"

[parallel]
track_mapping = "auto"

[geometry]
path        = "/home/wangchong/data/Hex-CMFD-v0.1/ant-moc-develop/cases/c5g7/simple-lattice/geometry.xml"
#path        = "cases/c5g7/simple-lattice/geometry.xml"
#path        = "/home/wangchong/data/Modify-Hex-CMFD/ant-moc-develop/cases/c5g7/simple-lattice/geometry.xml"
primitives  = ""
lattice_refines = "0, 0, 0"

[materials]
path      = "/home/gengxiaoxu/data/Hex-CMFD-v0.1/ant-moc-develop/cases/c5g7/c5g7-mgxs.h5"
#path      = "cases/c5g7/c5g7-mgxs.h5"
#path      = "/home/gengxiaoxu/data/Modify-Hex-CMFD/ant-moc-develop/cases/c5g7/c5g7-mgxs.h5"
xs_layout = "named"

[output]
reaction_rates = "F, PHI"
cross_sections = "none"
tracks         = "none"
mesh.type      = "rectangle"
mesh.offset    = "0, 0, 0"
mesh.shape     = "[1.26]*3, [1.26]*3, [1.428]*30"

[quadrature]
type         = "Equal Weight"
azims        = 16
azim_spacing = 1.0
polars       = 2
z_spacing    = 0.75

[ray_tracing]
segmentation = "OTF Stacks"
z_mesh       = "Local"
zones        = "-21.42, +21.42"
modules      = "1, 1, 1"

[solver]
type           = "CPU Solver"
max_iterations = 1000
tolerance      = 1E-5
stabilization  = "none"
keff_neutron_balance = false
